UptoiaOfGamers_Project/Utopia/urls.py
from django.urls import path
from rango import views
app_name = 'rango'

urlpatterns = [
 path('', views.index, name='index'),
 path('about/', views.about, name='about'),
 path('category/<slug:category_name_slug>/',views.show_category, name='show_category'),
 path('add_category/', views.add_category, name='add_category'),
 path('category/<slug:category_name_slug>/add_page/',views.add_page,name='add_page'),
 path('register/', views.register, name='register'),
 path('login/', views.user_login, name='login'),
 path('restricted/', views.restricted, name='restricted'),
 path('logout/', views.user_logout, name='logout'),
]

UptoiaOfGamers_Project/Utopia_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from rango import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
path('', views.index, name='index'),
path('rango/', include('rango.urls')),
path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

UptoiaOfGamers_Project/Utopia/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

class Category(models.Model):
   name = models.CharField(max_length=128, unique=True)
   views = models.IntegerField(default=0)
   likes = models.IntegerField(default=0)
   
   slug = models.SlugField(unique=True)

   
   def save(self, *args, **kwargs):
       self.slug = slugify(self.name)
       super(Category,self).save(*args, **kwargs)
       
   class Meta:
       verbose_name_plural = 'categories'
       
   def __str__(self):
       return self.name
      
    




      
class Page(models.Model):

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)
    
    def __str__(self):
       return self.title
       
class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)
    def __str__(self):
       return self.user.username

UptoiaOfGamers_Project/Utopia/forms.py
from django import forms
from rango.models import Page, Category
from django.contrib.auth.models import User
from rango.models import UserProfile

class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128, help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    slug = forms.CharField(widget=forms.HiddenInput(), required=False)


    class Meta:

        model = Category
        fields = ('name',)


class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128, help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200, help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    
    def clean(self):
          cleaned_data = self.cleaned_data
          url = cleaned_data.get('url')

          if url and not url.startswith('http://'):
           url = f'http://{url}'
           cleaned_data['url'] = url
          return cleaned_data

    class Meta:

        model = Page


        exclude = ('category',)
class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')

class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('website', 'picture')

UptoiaOfGamers_Project/Utopia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category
from rango.models import Page
from rango.forms import CategoryForm
from rango.forms import PageForm
from django.shortcuts import redirect
from django.urls import reverse
from rango.forms import UserForm, UserProfileForm
from django.contrib.auth import authenticate, login
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

 
@login_required
def restricted(request):
    return HttpResponse("Since you're logged in, you can see this text!")
 
def index(request):

     category_list = Category.objects.order_by('-likes')[:5]
     page_list = Page.objects.order_by('-views')[:5]
     context_dict = {'categories':category_list,'pages':page_list}
     context_dict['boldmessage'] = 'Crunchy, creamy, cookie, candy, cupcake!'
     context_dict['categories'] = category_list

     return render(request, 'rango/index.html', context=context_dict)

def about(request):
    context_dict = {'boldmessage': "Crunchy, creamy, cookie, candy, cupcake!"}
    return render(request, 'rango/about.html', context=context_dict)
    
def show_category(request, category_name_slug):

    context_dict = {}
    try:

        category = Category.objects.get(slug=category_name_slug)

        pages = Page.objects.filter(category=category)

        context_dict['pages'] = pages

        context_dict['category'] = category
    except Category.DoesNotExist:

        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context=context_dict)    


def add_category(request):

    if request.method == 'POST':
        form = CategoryForm(request.POST)


        if form.is_valid():

            form.save(commit=True)

            return index(request)
        else:

            print (form.errors)
    else:

        form = CategoryForm()

    return render(request, 'rango/add_category.html', {'form': form})
    
    
def add_page(request, category_name_slug):
   try:
      category = Category.objects.get(slug=category_name_slug)
   except Category.DoesNotExist:
      category = None

   if category is None:
      return redirect('/rango/')
   form = PageForm()
   if request.method == 'POST':
      form = PageForm(request.POST)
      if form.is_valid():
        if category:
           page = form.save(commit=False)
           page.category = category
           page.views = 0
           page.save()
           return redirect(reverse('rango:show_category',
                         kwargs={'category_name_slug':
                         category_name_slug}))
      else:
        print(form.errors)
        
   context_dict = {'form': form, 'category': category}
   return render(request, 'rango/add_page.html', context_dict)
   
   
def register(request):


    registered = False


    if request.method == 'POST':

        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)


        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save()


            user.set_password(user.password)
            user.save()



            profile = profile_form.save(commit=False)
            profile.user = user


            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']


            profile.save()


            registered = True

        else:
            print (user_form.errors, profile_form.errors)


    else:
        user_form = UserForm()
        profile_form = UserProfileForm()


    return render(request,
            'rango/register.html',
            {'user_form': user_form, 'profile_form': profile_form, 'registered': registered} )
            
def user_login(request): 
 if request.method == 'POST':

          username = request.POST.get('username')
          password = request.POST.get('password')

          user = authenticate(username=username, password=password)

          if user:
             if user.is_active:
                login(request, user)
                return redirect(reverse('rango:index'))
             else:

                return HttpResponse("Your Rango account is disabled.")
          else:

            print(f"Invalid login details: {username}, {password}")
            return HttpResponse("Invalid login details supplied.")
 else:

        return render(request,'rango/login.html')


@login_required
def user_logout(request):

    logout(request)

    return redirect(reverse('rango:index'))
  

UptoiaOfGamers_Project/templates/Utopia/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>
		    Utopia Of Gamers | 
			{% block title_block %}
			{% endblock %}
		<img src="images/UtopiaIcon.jpg" width="258" height="39" />
		</title>
	<p>Time is</p>	
	<script type="text/javascript" src="{% static 'js/time.js' %}"></script>
	<link rel='stylesheet' href="{% static 'css/style.css' %}">
	</head>
	<body>

<div>
            <ul type="square">			
			  <li><a href="{% url 'rango:News' %}">News</a></li>
			  <li><a href="{% url 'rango:Games' %}">Games</a></l\i>     			  		  
              <li><a href="{% url 'rango:about' %}">About</a></li>
			  <li><a href="{% url 'rango:index' %}">Index</a></li>
			  <hr>
			  
		 {% if user.is_authenticated %}
			  <li><a href="{% url 'rango:logout' %}">Logout</a></li>
			  <li><a href="{% url 'rango:Account' %}">My Account</a></l\i>
			{% else %} 
              
			  <li><a href="{% url 'rango:register' %}">Sign Up</a></li>
			  <li><a href="{% url 'rango:login' %}">Login</a></li>
            </ul>
        </div>
	</body>
</html>

UptoiaOfGamers_Project/templates/Utopia/index.html
{% extends 'utopia/base.html' %}
{% load staticfiles %}

{% block title_block %} 
Homepage.
{% endblock %}

{% block body_block %}
      <h1> Utopia Of Gamers</h1>
      {% if user.is_authenticated %}
        Good day, dear user {{ user.username }}!
      {% else %}
        Hi, visitor!
      {% endif %}
      <strong>{{ Gamecategory }}</strong>
      {% if Gamecategories %}
          <ul>
            {% for Gamecategory in Gamecategories %}
            <li>
               <a href="/rango/category/{{ category.slug }}/">{{ Gamecategory.name }}</a>
            </li>
            {% endfor %}
          </ul>
      {% else %}
           <strong>There are no Gamecategories present.</strong>
		   		   
      {% endif %}
        <hr>
	    <h1>Most Liked games</h1>
		 {%if games %}
		 <ul>
		    {% for game in games %}
			<li>
				<a href="{{ game.url }}">{{ game.title }}</a>
			<li>	
            {% endfor %}
		 <ul>	
		 {% else %}
           <strong>There is no gamess present.</strong>
         {% endif %}
		 
		<hr>
		<h1>Hottest news</h1>
		 {%if news %}
		 <ul>
		    {% for new in news %}
			<li>
				<a href="{{ new.url }}">{{ new.title }}</a>
			<li>	
            {% endfor %}
		 <ul>	
		 {% else %}
           <strong>There is no news present.</strong>
         {% endif %}
		 
		 
		 
{% endblock %}				 
         